name: Snyk
on:
  push:
    branches:
      - master
      - chore/CDX-785

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - name: Snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npx snyk monitor --dev --all-projects
          npx snyk test --dev --all-projects --sarif-file-output=./sarifs/snyk.sarif
          npx snyk code --dev --all-projects --sarif-file-output=./sarifs/snyk-code.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: ./sarifs
