name: Snyk
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2
      - name: Prepare snyk
        run: yarn install --no-immutable
      - name: Snyk Monitor
        continue-on-error: true
        if: ${{ github.event_name != 'pull_request' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: npx snyk monitor      --dev --yarn-workspaces --exclude="project.json"
      - name: Snyk Test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: npx snyk test --dev --yarn-workspaces --exclude="project.json" --sarif-file-output=./sarifs/snyk.sarif
      - name: Snyk Code
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: npx snyk code test    --dev --all-projects --exclude="project.json" --sarif > ./sarifs/snyk-code.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1

        with:
          sarif_file: ./sarifs
